User story#9
SER516-Team-Morpheus/microservices pull request #42
Opened 2023-04-13 20:34 UTC by VinayChavhan

Added happiness service

2023-04-14 01:49 UTC, VidhinASU requested changes

2023-04-16 01:11 UTC, skuma251 commented
Please make sure you are not raising the PR directly for main, it should go to develop first and tested their, only then it can go to main

2023-04-22 18:31 UTC, VidhinASU commented on src/happinessservice/index.js
> +    token = await getToken(username, password)
The function getToken is not defined

2023-04-23 22:18 UTC, VinayChavhan reviewed
made all suggested changes, please review

2023-04-23 22:29 UTC, VidhinASU approved these changes

2023-04-23 22:34 UTC, shivanjay-wagh approved these changes
looks good

2023-04-23 22:35 UTC, merged